name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Add these permission settings
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create .env from repo vars/secrets
        run: |
          {
            echo "REACT_APP_TURNSTILE_SITE_KEY=${{ secrets.REACT_APP_TURNSTILE_SITE_KEY }}";
            echo "REACT_APP_PH_PROJECT_API_KEY=${{ secrets.REACT_APP_PH_PROJECT_API_KEY }}";
            echo "REACT_APP_ENABLE_ANALYTICS=${{ vars.REACT_APP_ENABLE_ANALYTICS || 'true' }}";
          } > .env
          echo ".env created (contents hidden)."

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build